name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build:prod
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
        env:
          SSH_KEY: ${{ secrets.STATOSCOPE_TECH_SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.STATOSCOPE_TECH_SSH_KNOWN_HOSTS }}

      - name: Upload
        run: |
          scp -r ./public statoscope.tech:statoscope.tech/public_tmp
          ssh statoscope.tech 'cd statoscope.tech; rm -rf public; mv public_tmp public'
          END

      - name: Restart server
        run: ssh statoscope.tech 'docker-compose build; ssh statoscope.tech 'docker-compose up -d'
