name: Upload main stats

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build:prod

      - uses: actions/upload-artifact@v2
        with:
          name: main-stats
          path: ./public/demo-stats.json
